import { GraphQLError } from "graphql";
import { KnownErrorType } from 'src/enums/KnownErrorType.js';

export class UserOperationError extends GraphQLError {
  constructor(message: UserOperationStatus) {
    super(message, {
      extensions: { code: "USER_OPERATION_ERROR" }
    });
    Object.defineProperty(this, "name", { value: KnownErrorType.USER_OPERATION_ERROR });
  }
}

export enum UserOperationStatus {
  NO_ACCESS_ERROR = "NO_ACCESS_ERROR",
  DUPLICATED_MEMBER_ERROR = "DUPLICATED_MEMBER_ERROR",
  MEMBER_NOT_FOUND_ERROR = "MEMBER_NOT_FOUND_ERROR",
  UNKNOWN_ACCESS_TYPE_ERROR = "UNKNOWN_ACCESS_TYPE_ERROR",
  MEMBER_ALREADY_HAS_PRIMARY_WRITER_ACCESS = "MEMBER_ALREADY_HAS_PRIMARY_WRITER_ACCESS",
  MEMBER_ALREADY_HAS_PRIMARY_ST_ACCESS = "MEMBER_ALREADY_HAS_PRIMARY_ST_ACCESS",
  MEMBER_ALREADY_HAS_TEAMADMIN_ACCESS = "MEMBER_ALREADY_HAS_TEAMADMIN_ACCESS",
  MEMBER_ALREADY_HAS_VOTING_ACCESS = "MEMBER_ALREADY_HAS_VOTING_ACCESS",
  ST_ACCESS_CAN_ONLY_ADD_TO_DECEASED_WRITER = "ST_ACCESS_CAN_ONLY_ADD_TO_DECEASED_WRITER",
  USER_CANNOT_BE_PRIMARY_AND_ST_MEMBER = "USER_CANNOT_BE_PRIMARY_AND_ST_MEMBER",
  USER_ALREADY_HAS_PRIMARY_WRITER_ACCESS = "USER_ALREADY_HAS_PRIMARY_WRITER_ACCESS",
  USER_ALREADY_HAS_PRIMARY_ST_ACCESS = "USER_ALREADY_HAS_PRIMARY_ST_ACCESS",
  CAN_NOT_EDIT_PRIMARY_WRITER = "CAN_NOT_EDIT_PRIMARY_WRITER",
  CAN_NOT_EDIT_ST_MEMBER_OWNER = "CAN_NOT_EDIT_ST_MEMBER_OWNER",
  CAN_NOT_GIVE_ACCESS_TO_DECEASED_WRITER = "CAN_NOT_GIVE_ACCESS_TO_DECEASED_WRITER",
  USER_EXIST_ERROR = "USER_EXIST_ERROR",
  USER_NOT_FOUND_ERROR = "USER_NOT_FOUND_ERROR",
  USER_CANNOT_EDIT_OWN_DATA = "USER_CANNOT_EDIT_OWN_DATA",
  USER_NOT_ACTIVE_ERROR = "USER_NOT_ACTIVE_ERROR",
  EMAIL_IN_USE_BY_USER = "EMAIL_IN_USE_BY_USER",
  EMAIL_IN_USE_BY_MEMBER = "EMAIL_IN_USE_BY_MEMBER",
  EMAIL_IN_COGNITO_BUT_NOT_IN_DB = "EMAIL_IN_COGNITO_BUT_NOT_IN_DB",
  CAN_NOT_RECREATE_ACTIVE_USER_ERROR = "CAN_NOT_RECREATE_ACTIVE_USER_ERROR",
  MAX_RETRIES_REACHED_ERROR = "MAX_RETRIES_REACHED_ERROR",
  EMAIL_CAN_NOT_REGISTER_WRITER_ERROR = "EMAIL_CAN_NOT_REGISTER_WRITER_ERROR",
  USER_NOT_IN_WRITER_REGISTER = "USER_NOT_IN_WRITER_REGISTER",
  SUB_ACCESS_AND_ACCESS_NOT_MATCH = "SUB_ACCESS_AND_ACCESS_NOT_MATCH",
  SUPER_ADMIN_SHOULD_HAVE_NO_SUB_ACCESS = "SUPER_ADMIN_SHOULD_HAVE_NO_SUB_ACCESS",
  ABN_NOT_FOUND = "ABN_NOT_FOUND"
}
